/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import SMIATI.DataAlumni;
import SMIATI.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kuroko
 */
public class Cari extends javax.swing.JFrame {

    private DefaultTableModel model;
    
    /**
     * Creates new form NewJFrame
     */
    public Cari() {
        initComponents();
        model = new DefaultTableModel();
        tabel.setModel(model);
        model.addColumn("Nama");
        model.addColumn("Nim");
        model.addColumn("Tahun Lulus");
        model.addColumn("Tempat KP");
        model.addColumn("IPK");
        model.addColumn("Riwayar Kerja");
        model.addColumn("Judul TA");
        model.addColumn("email");
        
        loadData();
    }
    
    public void loadData(){
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    
    try{
        Statement stat = (Statement)koneksi.getKoneksi().createStatement();
        String sql = "Select * From alumni";
        ResultSet res = stat.executeQuery(sql);
        
        while(res.next()){
            Object[] obj = new Object[8];
                obj[0] = res.getString("NAMA");
                obj[1] = res.getString("NIM");
                obj[2] = res.getString("Tahun_Lulus");
                obj[3] = res.getString("Tempat_KP");
                obj[4] = res.getString("IPK");
                obj[5] = res.getString("Riwayat_Kerja");
                obj[6] = res.getString("Judul_TA");
                obj[7] = res.getString("email");
            
            model.addRow(obj);
        }
    }   catch (SQLException err) {
        JOptionPane.showMessageDialog(null, err.getMessage());
    }
    }
    
    public void cari(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
    
    try{
        Statement stat = (Statement)koneksi.getKoneksi().createStatement();
        String sql = "Select * From alumni Where NAMA Like '%" + isiandata.getText() + "%'" +
                "OR NIM LIKE '%"+isiandata.getText()+"%'"+"OR Tahun_Lulus LIKE '%"+isiandata.getText()+"%'";
        ResultSet res = stat.executeQuery(sql);
        
        while(res.next()){
            Object[] obj = new Object[8];
                obj[0] = res.getString("NAMA");
                obj[1] = res.getString("NIM");
                obj[2] = res.getString("Tahun_Lulus");
                obj[3] = res.getString("Tempat_KP");
                obj[4] = res.getString("IPK");
                obj[5] = res.getString("Riwayat_Kerja");
                obj[6] = res.getString("Judul_TA");
                obj[7] = res.getString("email");
            
            model.addRow(obj);
        }
    }   catch (SQLException err) {
        JOptionPane.showMessageDialog(null, err.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        isiandata = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 116, 676, 347));

        isiandata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiandataActionPerformed(evt);
            }
        });
        getContentPane().add(isiandata, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 58, 288, 31));

        cari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 56, 88, 31));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 481, 82, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/82794.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        cari();
    }//GEN-LAST:event_cariActionPerformed

    private void isiandataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiandataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiandataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new DataAlumni().show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JTextField isiandata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
